# Page settings

baseurl = "https://ruiju.netlify.com/"
languageCode = "en-us"
title = "Rui Ju Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"
    
# Sidebar sections

    # Profile section
    [params.profile]
        name = "Rui Ju"
        tagline = "Future Data Scientist"
        avatar = "mypicture.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:jurui1998@163.com"
        title = "jurui1998@163.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+86 15801861260"
        title = "+86 15801861260"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//ruiju.netlify.com"
        title = "ruiju.netlify.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/ruiju"
        title = "linkedin.com/in/ruiju"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/RuiJu1998"
        title = "github.com/RuiJu1998"

      # [[params.contact.list]]
      #  class = "twitter"
      #  icon = "fa-twitter"
      #  url = "//twitter.com/username"
      #  title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Shanghai University of Finance and Economics"
        college = "School of Economics"
        dates = "2015 - 2019"

        [[params.education.list]]
        degree = "University of California, Berkeley"
        college = "Visiting student"
        dates = "2017 - 2018"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

       # [[params.language.list]]
       # language = "Russian"
       # level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Breakdance"

        [[params.interests.list]]
        interest = "Violin Grade 10"

      #  [[params.interests.list]]
      #  interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
  #  [params.summary]
  #      enable = true
  #      icon = "fa-user"
  #      title = "Career Profile"
  #      summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Oct, 2018-present"
        company = "The Nielsen Company"
        details = "Participated in the data analysis and modeling of economic indicators based on county-level data all over China, and created a PPT report; Used python to compute the projection factors based on the model to help estimate the total sales of Coke Cola all over China;Assisted in building city blocks for local agents to visit on QGIS."

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "2014 - 2015"
        company = "Google, London"
        details = ""

        [[params.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = ""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "R"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Python"
        level = "90%"

        [[params.skills.list]]
        skill = "SQL"
        level = "90%"

        [[params.skills.list]]
        skill = "Matlab"
        level = "85%"

        [[params.skills.list]]
        skill = "Java"
        level = "80%"

        [[params.skills.list]]
        skill = "C++"
        level = "75%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]