# Page settings

baseurl = "https://ruiju.netlify.com/"
languageCode = "en-us"
title = "Rui Ju Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"
    
# Sidebar sections

    # Profile section
    [params.profile]
        name = "Rui Ju"
        tagline = "Future Data Scientist"
        avatar = "mypicture.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:jurui1998@163.com"
        title = "jurui1998@163.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+86 15801861260"
        title = "+86 15801861260"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//ruiju.netlify.com"
        title = "ruiju.netlify.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/ruiju"
        title = "linkedin.com/in/ruiju"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/RuiJu1998"
        title = "github.com/RuiJu1998"

      # [[params.contact.list]]
      #  class = "twitter"
      #  icon = "fa-twitter"
      #  url = "//twitter.com/username"
      #  title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Shanghai University of Finance and Economics"
        college = "School of Economics"
        dates = "2015 - 2019"

        [[params.education.list]]
        degree = "University of California, Berkeley"
        college = "Visiting student"
        dates = "2017 - 2018"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Advanced"

       # [[params.language.list]]
       # language = "Russian"
       # level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Breakdance"

        [[params.interests.list]]
        interest = "Violin Grade 10"

      #  [[params.interests.list]]
      #  interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
  #  [params.summary]
  #      enable = true
  #      icon = "fa-user"
  #      title = "Career Profile"
  #      summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Oct, 2018-Jan, 2019"
        company = "The Nielsen Company"
        details = "Participated in the data analysis and modeling of economic indicators based on county-level data all over China, and created a PPT report;\n\nUsed python to compute the projection factors based on the model to help estimate the total sales of Coke Cola all over China;\n\nAssisted in building city blocks for local agents to visit on QGIS."

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "May, 2018-Jun, 2018"
        company = "Bank of China, Shanghai Branch"
        details = " Assisted with managing and maintaining customer information management systems using Hadoop;\n\nStudied the features and requirements of customer information management systems, and collected improvement advises from other divisions."

        [[params.jobs.list]]
        position = "Quantitative Analyst"
        dates = "Jul, 2016-Aug, 2016"
        company = "FXCM Consulting Limited, Huangpu Branch"
        details = "Learned and practiced forex trading skills for 14+ hours every day, and wrote daily reports based on both quantitative and fundamental analysis;\n\nCollaborated with team members in giving an in-depth presentation on investment skills of stock, fund and forex."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        # intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Climate Discourse:Polarized or Post-Political?"
        url = "https://docs.wixstatic.com/ugd/6e9de4_c5287d561ba142f695e081df4a258de3.pdf"
        tagline = "Helped Rachel Wetts (PhD, UCB) with analyzing the deciding factors of press releases concerned with climate change getting picked up by mainstream media."

        [[params.projects.list]]
        title = "Shoe Sales"
        url = "https://github.com/RuiJu1998/ShoeSales"
        tagline = "A time series analysis analyzing the monthly shoe sales throughout the US and making predictions using ARIMA models and spectral analysis."

        [[params.projects.list]]
        title = "Movie Collection"
        url = "https://github.com/RuiJu1998/MovieCollection"
        tagline = "A simple system for movie lovers to record the movies they have watched along with their personal ratings and reviews for them."
        
        [[params.projects.list]]
        title = "Scheme Interpreter"
        url = "https://github.com/RuiJu1998/SchemeInterpreter"
        tagline = "A simple scheme interpreter in Python."
        
        [[params.projects.list]]
        title = "Ants"
        url = "https://github.com/RuiJu1998/Ants"
        tagline = "A game in Python inspired by Plants vs. Zombies using object-oriented design."
        
        [[params.projects.list]]
        title = "Yelp Maps"
        url = "https://github.com/RuiJu1998/YelpMaps"
        tagline = "A visualization of restaurant ratings using machine learning and the Yelp academic dataset."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "R"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Python"
        level = "90%"

        [[params.skills.list]]
        skill = "SQL"
        level = "90%"

        [[params.skills.list]]
        skill = "Matlab"
        level = "85%"

        [[params.skills.list]]
        skill = "Java"
        level = "80%"

        [[params.skills.list]]
        skill = "C++"
        level = "75%"
        
        [[params.skills.list]]
        skill = "QGIS"
        level = "85%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
      copyright = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]